### ISSUE TITLE
Published ibroadcast package on PyPI

### ISSUE THREAD

**Issue by ctrueden** [Auzzy/ibroadcast-uploader-rewrite#13]
I published a [general-purpose iBroadcast Python client to PyPI](https://pypi.org/project/ibroadcast/). The package is called `ibroadcast` and requires Python 3. Contributions are welcome if you have time and interest. Feel free to close this issue; I just wanted to let you know.

**Comment by Auzzy** [comment]
Thanks for the heads up! I may circle back around to this script soon, and I'll take a look at your package when I do.
